export default {    
    AUTH_REQUEST:'AUTH_REQUEST',
    AUTH_SUCCESS:'AUTH_SUCCESS',	
	LOADING_CHANGE:'LOADING_CHANGE',
	AUTH_OFF:'AUTH_OFF',
	SEARCH_REQUEST:'SEARCH_REQUEST',
	SEARCH_SUCCESS:'SEARCH_SUCCESS',
	SEARCH_CLEAR:'SEARCH_CLEAR',
	SEARCH_SUCCESSRESET:'SEARCH_SUCCESSRESET'
}